AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5

Resources:
  GuilhunizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-build/guilhunize
      Runtime: go1.x
      Tracing: Active
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/guilhunize
            Method: POST
  QuoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-build/guilhunize
      Runtime: go1.x
      Tracing: Active
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/quote
            Method: GET

Outputs:
  GraphmanAPI:
  GuilhunizeFunction:
    Value: !GetAtt GuilhunizeFunction.Arn
