version: 2.1

orbs:
  moul: moul/build@1.12.1 # https://github.com/moul/build

workflows:
  main:
    jobs:
      - moul/golang-build:
          gopkg: moul.io/golang-repo-template
      - moul/golang-build:
          gopkg: moul.io/golang-repo-template
          tag: '1.12'
      - moul/golang-build:
          gopkg: moul.io/golang-repo-template
          tag: '1.11'
      - moul/docker-build
